### ISSUE TITLE
Suggested recipes page

### ISSUE THREAD

**Issue by nicmart-dev** [nicmart-dev/feedmenow#11]
As a user I want to see the recipes recommended to me and how it relates to the ingredients I have.

Dev notes:
- uses #7 workflow output
- filter component will be handled with #6 so can be considered out of scope here
- if save a recipe, user needs to log in #14, but not needed otherwise

Design notes: see related [wireframe](https://github.com/nicmart-dev/feedmenow/wiki/UI-wireframe-prototype-using-balsamiq):

![Image](https://github.com/nicmart-dev/feedmenow/assets/10499747/ed54d3d8-6a25-4ed7-b1f3-a1d028656e7f)

**Comment by nicmart-dev** [comment]
Design note: 

> rewrite the recipes in a uniform manner, a uniform recipe card for every recipe seems like it would make the whole website feel easier on the eyes

**Comment by juliakimseohyeon** [comment]
Created basic structure and style for Recipe Suggestion page.

[PR request is here](https://github.com/nicmart-dev/feedmenow/pull/34)
