### ISSUE TITLE
Recipe details

### ISSUE THREAD

**Issue by nicmart-dev** [nicmart-dev/feedmenow#22]
As a user I want to see full recipe details if I select a recipe I'm interested in, when I view suggested recipes, or my saved recipes.

See related [wireframe](https://github.com/nicmart-dev/feedmenow/wiki/UI-wireframe-prototype-using-balsamiq)
![Image](https://github.com/nicmart-dev/feedmenow/assets/10499747/3896dc6a-6832-4997-ab6d-c92e9dfb4163)

**Comment by juliakimseohyeon** [comment]
https://github.com/nicmart-dev/feedmenow/pull/30
Front-end UI has been completed and can be seen in the endpoint "/recipes/:id"

**Comment by juliakimseohyeon** [comment]
Look into "feature toggle" to hide the heart when it is not necessary
