### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by nicmart-dev** [nicmart-dev/feedmenow#24]
As a user I need to change language to one of the top 3 main languages used in Canada, which are English, French or Mandarin Chinese.

Dev notes:
* `strings.json` holds text strings translated from English using ChatGPT

Design document: https://github.com/nicmart-dev/feedmenow/wiki/Internationalization-using-react%E2%80%90intl-package

**Comment by nicmart-dev** [comment]
Sample code you can check: https://github.com/nicmart-dev/linguistnow/blob/main/client/src/components/Navbar.jsx

![Image](https://github.com/user-attachments/assets/dd59add9-3521-4380-abdb-93ea63d06369)

**Comment by nicmart-dev** [comment]
Updated design document explaining how to use `react-intl` package.

**Comment by juliakimseohyeon** [comment]
Language Button function has been added in the branch "feature/frontend-homescreen"
Pull Request for feature: https://github.com/nicmart-dev/feedmenow/pull/29
