### ISSUE TITLE
Recommend recipes using n8n workflow

### ISSUE THREAD

**Issue by nicmart-dev** [nicmart-dev/feedmenow#7]
Use an AI to suggest and format recipes based on ingredients list and preferences set.

Dev notes:
* list of ingredients and preferences can be hardcoded if #19 or #18 are not yet done
* workflow output is then shown to user in #11 (it can be further formatted there, but should have the relevant structure here)

Design document: https://github.com/nicmart-dev/feedmenow/wiki/Use-AI-to-recommend-recipes

**Comment by nicmart-dev** [comment]
Existing solution we can get inspired by: https://www.mskog.com/posts/recipe-extraction-with-n8n-and-chatgpt

**Comment by nicmart-dev** [comment]
Added draft to design document https://github.com/nicmart-dev/feedmenow/wiki/Use-AI-to-recommend-recipes

@yaacovkdev Based on our discussion and your interest to focus on ML/AI, I'm thinking you may want to work on this. If so, please assign yourself to this issue.

**Comment by juliakimseohyeon** [comment]
[Sample Prompt]
Take the input of ingredients and clean/organize them into a table.
If there is no weight or amount listed, then do not include it in the table.
Make it short and don't add explanations. If the input is not in English then translate it to English. Do not keep the other language.

Using the ingredients in the table, come up with recipes that could be created using these ingredients. Don't include recipes that require any missing ingredients. Each recipe should contain a name, serving amount, kcal, protein, carbs, fat, cooking time, cuisine type (i.e. French, Japanese, Mexican, etc), and number of ingredients from the table that will be required to cook the recipe.
Add a step-by-step cooking guide for the recipe. Avoid generic recipes like simple white rice or toast with jam that only require one or two ingredients. Return each recipe as its own JSON object.

[Sample Input]
5 eggs, 2 packs cherry tomatoes, 1 loaf whole wheat bread, sesame seeds, dried alpaca meat, garlic, salt, olive oil, potatoes, tortilla chips 500g, 1kg white rice, kimchi, instant ramen, rosemary
