### ISSUE TITLE
Send ingredients and start n8n workflow

### ISSUE THREAD

**Issue by nicmart-dev** [nicmart-dev/feedmenow#8]
As the system I need to get ingredients list and execute n8n workflow

Dev notes: 

- create new n8n workflow and invite 3 collaborators onto existing instance https://github.com/nicmart-dev/feedmenow/wiki/n8n-workflow
- handle submit through a new backend route that sends it and execute n8n workflow
- adding n8n workflow nodes after trigger node is covered with #7

**Comment by nicmart-dev** [comment]
Installed 12 months enterprise license on https://n8n.nicmart.synology.me and invited my two team mates.

**Comment by nicmart-dev** [comment]
Created recipes api route https://github.com/nicmart-dev/feedmenow/pull/28

Now I need to work on basic UI field to define ingredients parameter.

**Comment by juliakimseohyeon** [comment]
Created basic UI for homescreen in the branch "feature/frontend-homescreen"

**Comment by nicmart-dev** [comment]
Home UI has now been covered by Julia in #21
